export enum ProductRefreshReason {
  CREATED = 'CREATED',
  OFFER_UPDATED = 'OFFER_UPDATED',
  PENDING_RESEND = 'PENDING_RESEND',
  ADOPTED = 'ADOPTED',
  EXPIRED = 'EXPIRED',
  REQUESTED = 'REQUESTED',
}
