app:
  port: 5000

datasource:
  host: localhost
  port: 5432
  username: postgres
  password: password
  database: gmc_db

rabbitmq:
  uri: amqp://guest:guest@localhost:5672
  prefetch-count:

aws:
  id:
  secret:
  region: us-east-1
