port: 5002

datasource:
  host: gmc_postgres
  port: 5432
  username: postgres
  password: password
  database: gmc_db
  migrate:

rabbitmq:
  uri: amqp://guest:guest@gmc_rabbitmq:5672
  prefetch-count:

aws:
  id:
  secret:
  region: us-east-1

rainforest:
  zip-code: SE21 8AX
  api_key:

elastic:
  username: elastic
  password: changeme
  node: http://gmc_elasticsearch:9200
  index: gmc_search
